package com.ethopia.tradecabinet.model.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import com.ethopia.tradecabinet.model.AppFeatureAccess;
import com.ethopia.tradecabinet.model.AppGroupRole;
import com.ethopia.tradecabinet.model.AppUserRole;

/**
 * Class _AppRole was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AppRole extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<String> ROLE_NAME = Property.create("roleName", String.class);
    public static final Property<List<AppFeatureAccess>> APPFEATUREACCESSES = Property.create("appfeatureaccesses", List.class);
    public static final Property<List<AppGroupRole>> APPGROUPROLES = Property.create("appgrouproles", List.class);
    public static final Property<List<AppUserRole>> APPUSERROLES = Property.create("appuserroles", List.class);

    protected String description;
    protected String roleName;

    protected Object appfeatureaccesses;
    protected Object appgrouproles;
    protected Object appuserroles;

    public void setDescription(String description) {
        beforePropertyWrite("description", this.description, description);
        this.description = description;
    }

    public String getDescription() {
        beforePropertyRead("description");
        return this.description;
    }

    public void setRoleName(String roleName) {
        beforePropertyWrite("roleName", this.roleName, roleName);
        this.roleName = roleName;
    }

    public String getRoleName() {
        beforePropertyRead("roleName");
        return this.roleName;
    }

    public void addToAppfeatureaccesses(AppFeatureAccess obj) {
        addToManyTarget("appfeatureaccesses", obj, true);
    }

    public void removeFromAppfeatureaccesses(AppFeatureAccess obj) {
        removeToManyTarget("appfeatureaccesses", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<AppFeatureAccess> getAppfeatureaccesses() {
        return (List<AppFeatureAccess>)readProperty("appfeatureaccesses");
    }

    public void addToAppgrouproles(AppGroupRole obj) {
        addToManyTarget("appgrouproles", obj, true);
    }

    public void removeFromAppgrouproles(AppGroupRole obj) {
        removeToManyTarget("appgrouproles", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<AppGroupRole> getAppgrouproles() {
        return (List<AppGroupRole>)readProperty("appgrouproles");
    }

    public void addToAppuserroles(AppUserRole obj) {
        addToManyTarget("appuserroles", obj, true);
    }

    public void removeFromAppuserroles(AppUserRole obj) {
        removeToManyTarget("appuserroles", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<AppUserRole> getAppuserroles() {
        return (List<AppUserRole>)readProperty("appuserroles");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "description":
                return this.description;
            case "roleName":
                return this.roleName;
            case "appfeatureaccesses":
                return this.appfeatureaccesses;
            case "appgrouproles":
                return this.appgrouproles;
            case "appuserroles":
                return this.appuserroles;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "description":
                this.description = (String)val;
                break;
            case "roleName":
                this.roleName = (String)val;
                break;
            case "appfeatureaccesses":
                this.appfeatureaccesses = val;
                break;
            case "appgrouproles":
                this.appgrouproles = val;
                break;
            case "appuserroles":
                this.appuserroles = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.description);
        out.writeObject(this.roleName);
        out.writeObject(this.appfeatureaccesses);
        out.writeObject(this.appgrouproles);
        out.writeObject(this.appuserroles);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.description = (String)in.readObject();
        this.roleName = (String)in.readObject();
        this.appfeatureaccesses = in.readObject();
        this.appgrouproles = in.readObject();
        this.appuserroles = in.readObject();
    }

}
